### ISSUE TITLE
Error: Missing credentials in config when using AWS_WEB_IDENTITY_TOKEN_FILE

### ISSUE THREAD

**Issue by sbkg0002** [alexjurkiewicz/ecr-scan-image#16]
When using [AWS Federation](https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html), the `AWS_WEB_IDENTITY_TOKEN_FILE` is set (and no AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY is used).

GHA:
```yaml
# https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions
- name: Login to Amazon ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v1

# https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions
- name: Build, tag, and push image to Amazon ECR
  env:
    # Static
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    IMAGE_TAG: ${{ github.sha }}
  run: |
    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker/
    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

# https://github.com/marketplace/actions/aws-ecr-scan-docker-image
- name: Scan Docker image
  id: docker-scan
  uses: alexjurkiewicz/ecr-scan-image@v1.6.1
  env:
    # Static
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    IMAGE_TAG: ${{ github.sha }}
  with:
    repository: $ECR_REGISTRY/$ECR_REPOSITORY
    tag: $IMAGE_TAG
    fail_threshold: high
```
Both the login and the build&push succeed, but the scan fails with:
```
Error: Missing credentials in config
```

Any idea why this might fail?

Thanks in advance!
