### ISSUE TITLE
Issue scanning images built with buildx and OCI image manifest

### ISSUE THREAD

**Issue by altmas5** [alexjurkiewicz/ecr-scan-image#43]
Hi,

I am new using this action, it looks it does not support the OCI image manifest:
```
Requesting image scan
Error: An artifact with media type 'application/vnd.oci.image.index.v1+json' cannot be scanned. For more information, see the Amazon ECR documentation.
```

I am adding this issue in case anyone encounters the same.

**Comment by altmas5** [comment]
Nevermind, it seems to be an issue on ECR
https://github.com/moby/buildkit/issues/3499

**Comment by altmas5** [comment]
This was my solution:
```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.9.1
```
